# -*- coding: utf-8 -*-
"""Sufriani.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s9xyVu_65ZDpqZdGe2-4zJVpYYdAUdJh
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
from sklearn.metrics import precision_score, recall_score, accuracy_score

import os

import warnings

warnings.filterwarnings('ignore')

data = 'belajar dataset.csv'

df = pd.read_csv('belajar dataset.csv')

df.shape

df.head()

df.describe()

df.info()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

selected_columns = ['Bulan Ke']
X = df[selected_columns]
y = df['Jumlah Panen Padi Dalam Ton']

X.info()

X.head()

cols = X.columns

from sklearn.preprocessing import MinMaxScaler

ms = MinMaxScaler()

X = ms.fit_transform(X)

X = pd.DataFrame(X, columns=[cols])

X.head()

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0)

kmeans.fit(X)

label_2 = kmeans.fit_predict(X)

kmeans.inertia_

kmeans.cluster_centers_

selected_columns = ['Bulan Ke', 'Jumlah Panen Padi Dalam Ton']
if all(col in df.columns for col in selected_columns):
    X = df[selected_columns]
    y = df['Jumlah Panen Padi Dalam Ton']

    plt.scatter(X['Bulan Ke'], X['Jumlah Panen Padi Dalam Ton'], c=kmeans.labels_)
    plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 0], marker='x', color='red')
    plt.xlabel('Bulan Ke')
    plt.ylabel('Jumlah Panen Padi Dalam Ton')
    plt.title('K-Means Clustering K = 2')
    plt.show()
else:
    print("Kolom yang diminta tidak tersedia dalam DataFrame.")

inertia = []
for k in range(1, 16):
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 16), inertia, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('Inersia')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=0)
kmeans.fit(X)
label_4 = kmeans.labels_

plt.scatter(X['Bulan Ke'], X['Jumlah Panen Padi Dalam Ton'], c=label_4)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], marker='x', color='red')
plt.xlabel('Bulan Ke')
plt.ylabel('Jumlah Panen Padi Dalam Ton')
plt.title('K-Means Clustering K = 4')
plt.show()

df['k=2'] = label_2
df['k=4'] = label_4
print(df)
df.to_csv('k-means-result.csv', index=False)